# Generated by Django 3.2.4 on 2021-08-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nome_atendente',
            field=models.CharField(default='atendente', max_length=30),
        ),
    ]
