# Generated by Django 3.2.4 on 2021-08-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentoapp', '0002_pedido_nome_atendente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'ordering': ['procedimento']},
        ),
    ]
