# Generated by Django 3.2.4 on 2021-08-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentoapp', '0003_alter_procedimento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='nome_atendente',
        ),
    ]
